
var ArchiveString = {
	   Configuration : "Configuration",
	   Home : "Home",
	   LibraryFiles : "Library Files",
	   IncludeTestBench : "Include TestBench",
	   OutputFiles : "Output Files",
	   AdditionalFiles : "Additional Files",
	   Referencedprojects : "Referenced Projects",
	   Mode : "Select Mode",
	   ArchiveDirectory : "Archive Directory",
	   ArchiveProject : "Select Directory",
	   SaveProject : "Save Project As",
	   Settings : "Settings",
	   OK : "OK",
	   Cancel : "Cancel",
	   Help : "Help",
	   CreateSingleArchiveFile : "Create Single Archive File",
	   FileName : "File Name",
	   AddMoreFiles : "Add More Files",
	   Archive: "Archive",
	   Path: "Enter Destination Path",
	   Browse: "...",
	   Help: "Help",
	   Destination: "Destination Directory",
	   DestinationFileName: "Project Name",
	   Compress: "Compressed",
	   EDMM_CWR : "Copy All Referred Files Present Within Project Folder",
	   EDMM_COR : "Copy All Referred Files Present Out of Project Folder",
	   EDMM_COPY_RELATIVE_PATH_WITHIN_ROOT : "Copy Relative Path Within Root",
	   EDMM_COPY_ABSOLUTE_PATH_WITHIN_ROOT : "Copy Absolute Path Within Root",
	   EDMM_COPY_RELATIVE_PATH_OUTOF_ROOT : "Copy Relative Path Out of Root",
	   EDMM_COPY_ABSOLUTE_PATH_OUTOF_ROOT : "Copy Absolute Path Out of Root",
	   EDMM_COPY_ALL : "Copy all",
	   EmptyDirectory		: "Empty Directory: Please Enter a Valid Directory",
	   EmptyProjectName		: "Empty Project Name: Please Enter a Project Name",
	   EmptyPath	   		: "Empty Path: Please Enter a Valid Path",
	   InvalidExtension		: "Invalid Extension: Please Enter a Project Name with .opj Extension",
	   EmptyArchiveFile		: "Empty Compressed File Name: Please Enter a Valid Archive File Name",
	   InvalidArchiveFileName : "Invalid Compressed File Name: Archive File Name Should end with .zip ",
	   EDMM_MD				: "Settings for Copied Design",
	   EDMM_USE_RELATIVE_PATH_FOR_MOVED_DESIGNS : "Use Relative Path for Copied Design",
	   SameProjectError 	: "Same Project Exist: Please choose either Different Name or Different Folder",
	   InvalidProjectName	: "Invalid Project Name: Please Enter a valid Project Name",
	   InvalidDirectory		: "Directory Error: Either Directory Name is invalid or Directory do not have write permissions",
	   Rename				: "Rename DSN to match Project",
	   Copy					: "Copy DSN to Project Folder",
	   ReferredInfo			: "*Referred Files include Referred Projects, Libraries, Output Files, Simulation Files etc.. "

};
