# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.


package ifneeded PspAATcl 16.6.0 [list load orpsppmpsvr.dll PspAATcl]
package ifneeded PspAACtrlTcl 16.6.0 [list load oradvctrlr.dll PspAACtrlTcl]
package ifneeded PSpiceAA 16.6.0 [list load pspiceaa.exe PSpiceAA]

package ifneeded PspAARunAnalysisUtil 1.0 [list source [file join $dir PspAARunAnalysisUtil.tcl]]
package ifneeded pspAAUI 1.0 [list source [file join $dir pspAAUI.tcl]]
package ifneeded pspAATempSweepMc 1.0 [list source [file join $dir pspAATempSweepMc.tcl]]
