# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded capFPViewerUtils 1.0 [list source [file join $dir capFPViewerUtils.tcl]]
package ifneeded capMenuUtil 1.0 [list source [file join $dir capMenuUtil.tcl]]
package ifneeded capSessionUtil 1.0 [list source [file join $dir capSessionUtil.tcl]]
package ifneeded capSyncPropPCBFootprint 1.0 [list source [file join $dir capSyncPropPCBFootprint.tcl]]
package ifneeded capPdfLaunch 1.0 [list source [file join $dir capPdfLaunch.tcl]]
package ifneeded capPdfUtil 1.0 [list source [file join $dir capPdfUtil.tcl]]
package ifneeded capGeom 1.0 [list source [file join $dir capGeom.tcl]]
package ifneeded capTextUtils 1.0 [list source [file join $dir capTextUtils.tcl]]
package ifneeded capCommServerLaunch 1.0 [list source [file join $dir capCommServerLaunch.tcl]]
package ifneeded capCommServer 1.0 [list source [file join $dir capCommServer.tcl]]
package ifneeded capReplacePathInCacheUtil 1.0 [list source [file join $dir capReplacePathInCache.tcl]]
package ifneeded capAnnotateHBlockPageNumberLaunch 1.0 [list source [file join $dir capAnnotateHBlockPageNumberLaunch.tcl]]
package ifneeded capReplacePathInCacheUtilLaunch 1.0 [list source [file join $dir capReplacePathInCacheUtilLaunch.tcl]]
package ifneeded capSearchExecute 1.0 [list source [file join $dir capSearchExecute.tcl]]
package ifneeded capNetNamesCorrection 1.0 [list source [file join $dir capCorrectNetnamesONL.tcl]]
package ifneeded capFindUtil 1.0 [list source [file join $dir capFindUtil.tcl]]
package ifneeded OrCommonTcl 16.6.0 [load orCommonTcl.dll OrCommonTcl ]
package ifneeded orParser 1.0 [load orParserTcl.dll orParser ]
package ifneeded capRecurseParts 1.0 [list source [file join $dir capRecurseParts.tcl]]
package ifneeded capFindUserEdits 1.0 [list source [file join $dir capFindUserEditedReferences.tcl]]
