# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded OrCommonTcl 1.0 [list load orCommonTcl.dll orCommonTcl]
package ifneeded PspCtrlTcl 16.6.0 [list load orpsp_wobj.dll PspCtrlTcl]
package ifneeded orPSpiceIBISParser 16.6.0 [list load orPSpiceIBISParser.dll orPSpiceIBISParser]
package ifneeded ibistopspice 1.0 [list source [file join $dir ibistopspice.tcl]]
package ifneeded ibisnetlist 1.0 [list source [file join $dir ibisnetlist.tcl]]
