#!/bin/csh -f

# test program for Allegro email 
#  point  cdn_mail_unix  env variable to this file for test purposes
#  to override Allegro email facility

set file =  cdn_output.txt
echo ============================================ >> $file
echo DATE- `date` >> $file
cat $argv[1] >> $file
