// JScript source code


function SelectType(){
arg=unescape((''+self.location.search));
var pattern1=new RegExp("all");
if ((pattern1.test(arg))===false){
var params = arg.split("?")[1].split("&");
var v1=params[0].split("=");
var v2=params[1].split("=");
type=v1[1];
RefDes=v2[1];
mode="";
}
else {type = "all";
mode="startup";
}
}

function orPrmNativeCall(method, params)
{
var ret = "Tcl interface not available";
if(null !== window.external.orPrmWidgetId)
{
ret = window.external.orPrmConnector(method, params);
}
else
{
// perform processing without Tcl interface
}
return ret;
}
//


function Header(name)
{
header="*******************************************" + "\n" + "*Model Generated by PSpice Modeling Apps  *" + "\n" + "*Copyright(c) Cadence Design Systems      *" + "\n" + "*All Rights Reserved                      *" + "\n" + "*******************************************" + "\n" + "* Model generated on ";
day = new Date();
var month_names = new Array(12);
month_names[0] = "Jan";
month_names[1] = "Feb";
month_names[2] = "Mar";
month_names[3] = "Apr";
month_names[4] = "May";
month_names[5] = "Jun";
month_names[5] = "Jun";
month_names[6] = "Jul";
month_names[7] = "Aug";
month_names[8] = "Sep";
month_names[9] = "Oct";
month_names[10] = "Nov";
month_names[11] = "Dec";

header = header + month_names[day.getMonth()] + " " + day.getDate() +  " " + day.getYear() +"\n" + "* MODEL FORMAT: PSpice" + "\n" + "* MODEL Type: " +name + "\n";
return header;
}
//Start of Subckt function

function Close_View(){
orPrmNativeCall("executeTcl", "MenuCommand \"57927\"");
}

function Write_Model(){

orPrmNativeCall("executeTcl", "::capPSpiceModelAppBase::UpdateModel " + ModelName);
orPrmNativeCall("executeTcl", "::capPSpiceModelAppBase::WriteModel " + "{"+ ModelText +"} " + SYM + " " + ModelName);

}
function Place_Part(name){

orPrmNativeCall("executeTcl", "::capPSpiceModelAppBase::PlaceSym " + name + " " + ModelName);
}

function Write_InputData(updatedModel){

JsData = orPrmNativeCall("executeTcl", "::capPSpiceModelAppBase::WriteJs " + "{" + updatedModel + "}");

}

function Read_InputData(){
orPrmNativeCall("executeTcl", "::capPSpiceModelAppBase::CreateAppsDir");
orPrmNativeCall("executeTcl", "::capPSpiceModelAppBase::ReadJs");
JsStrgData = orPrmNativeCall("executeTcl", "::capPSpiceModelAppBase::ReadJs ");
ModelJsData = JSON.parse(JsStrgData);
return ModelJsData;
}


function AddTransformerUIData(type) {
var NewM = {"Name":RefDes , "Type":type, "LP1": document.getElementById(type).N1.value, "RP1": document.getElementById(type).Rp1.value, "RS1": document.getElementById(type).RS1.value, "Couplig":document.getElementById(type).coupling.value, "TRaio":document.getElementById(type).ratio.value , "WDGNO":"12"};
}

